name: Deploy to Vercel

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-skip:
    uses: ./.github/workflows/skip-vercel.yml

  deploy:
    needs: check-skip
    if: needs.check-skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DECK_ANALYZER_MODE: off

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        timeout-minutes: 2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Run linting
        run: npm run lint 2>/dev/null || echo "No lint script found, skipping"
        timeout-minutes: 3

      - name: Run tests
        run: npm test 2>/dev/null || echo "No test script found, skipping"
        timeout-minutes: 5

      - name: Build application
        run: npm run build
        timeout-minutes: 8

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Comment on PR (if PR deployment)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview deployment ready!**\n\nYour changes have been deployed to Vercel. Check it out: ${{ steps.deploy.outputs.vercel-url }}`
            })
