name: Project Field Mapper
on:
  issues:
    types: [labeled, opened]
  pull_request:
    types: [labeled, opened, ready_for_review]
permissions:
  contents: read
  issues: write
  pull-requests: write
env:
  CONNECT_TIMEOUT: 5
  MAX_TIME: 30
  RETRY_COUNT: 5
  RETRY_MAX_TIME: 40
  SPEED_TIME: 10
  SPEED_LIMIT: 1024
  EXPECT100_TIMEOUT: 2
  BACKOFF_BASE: 1
jobs:
  map_fields:
    runs-on: ubuntu-latest
    steps:
      - name: Map fields from labels
        uses: leonsteinhaeuser/project-beta-automations@v2.5.1
        with:
          gh_token: ${{ secrets.PROJECTS_TOKEN }}
          user: "alanherron"
          project_id: "2"
          resource_node_id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          field_mappings: |
            Area=Library:label:Library
            Area=Deckbuilder:label:Deckbuilder
            Area=AI:label:AI
            Area=Infra:label:Infra
            Area=Design:label:Design
            Area=Docs:label:Docs
            Priority=P0:label:P0
            Priority=P1:label:P1
            Priority=P2:label:P2
            Priority=P3:label:P3
            Status=Backlog:label:backlog
            Status=In Progress:label:in-progress
