name: Project Auto

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  project: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to Scrylytics Roadmap
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/alanherron/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}name: Project Auto
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
permissions:
  contents: read
  issues: write
  pull-requests: write
  project: write
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to Scrylytics Roadmap
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/alanherron/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
